#!/bin/bash

expression="$1"
directory="$2"

if [ -z "$expression" ]
then
	echo "Usage: $0 <expression> [<directory>]"
	exit 1
fi

if [ -z "$directory" ]
then
	directory="."
fi

grep \
	$3 \
	--color       \
	--recursive   \
	--mmap        \
	--line-number \
	-I            \
	--include="*.cpp"      \
	--include="*.cc"       \
	--include="*.c"        \
	--include="*.hpp"      \
	--include="*.h"        \
	--include="*.s"        \
	"$expression"          \
	$directory

exit $?

