#!/bin/bash

expression="$1"
directory="$2"

if [ -z "$expression" ]
then
	echo "Usage: $0 <expression> [<directory>]"
	exit 1
fi

if [ -z "$directory" ]
then
	directory="."
fi

grep \
	--color \
	--recursive \
	--mmap \
	--line-number \
	-I \
	--no-messages \
	"$expression" \
	$directory

exit $?

