set autoindent

set ts=4
set shiftwidth=4
set softtabstop=4
set noexpandtab

set nowrap
set incsearch
set hlsearch
set ignorecase
set smartcase

set showmatch

"set colorcolumn=+1     " highlight col after 'textwidth'
":highlight ColorColumn ctermbg=238 guibg=lightgrey
"set colorcolumn=100

syntax on
filetype on

set nobackup

set tags=tags;/

:map <Down> gj
:map <Up> gk

noremap j gj
noremap k gk

" https://vi.stackexchange.com/a/2285
" Remove all trailing whitespace by pressing F5
nnoremap <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>
nnoremap <F6> :let _s=@/<Bar>:%s///e<Bar>:let @/=_s<Bar><CR>

"let g:clang_format#command = "/opt/llvm-16.0.4/bin/clang-format"
let g:clang_format#command = "/nfs/site/home/smithj1/code/system-controller.firmware/scripts/vim-clang-format-wrapper.sh"
let g:clang_format#auto_format = 1
let g:clang_format#detect_style_file = 1
let g:clang_format#auto_filetypes = [ "c", "cpp" ]
let g:clang_format#enable_fallback_style = 0

set runtimepath^=~/.vim/custom/context.vim

