#!/bin/bash
#
# beep [<exitCode> [<customMsg>]]
#
#  <exitCode>   - Optional exit code of the operation that is causing the notification.
#  <customMsg>  - Optional custom message to display in the dialog box (if applicable).
#

exitcode="${1}"
shift
message="${@}"

# always try the audible beep
printf '\a'

if which zenity &>/dev/null
then
	msgtext="Beep"
	msgtype="--info"

	if [[ -n "${exitcode}" ]]
	then
		if [[ "${exitcode}" == "0" ]]
		then
			msgtext="Operation successful"
			msgtype="--info"
		else
			msgtext="Operation failed"
			msgtype="--error"
		fi

		[[ -n "${message}" ]] && msgtext="${msgtext}:\n\n<tt><big>${message}</big></tt>"
	fi

	zenity                   \
		${msgtype}           \
		--text="${msgtext}"  \
		--no-wrap            \
		2>/dev/null &

else
	echo "Error zenity not found, no popup available"
fi

exit 0

